//! Persistent storage for the Iroh secret key that defines one Rift device.
//!
//! The storage envelope detects format errors and ordinary corruption. Foundation M4
//! relies on the operating-system user and filesystem boundary for confidentiality;
//! the secret key is not encrypted at rest.

use std::{
    fmt,
    fs::{self, File, OpenOptions},
    io::{self, Write},
    path::{Path, PathBuf},
    sync::atomic::{AtomicU64, Ordering},
};

use iroh::SecretKey;
use rift_core::DeviceId;
use thiserror::Error;

const IDENTITY_MAGIC: &[u8; 8] = b"RIFTIDEN";
const SECRET_KEY_LEN: usize = 32;
const CHECKSUM_LEN: usize = 32;
const PREFIX_LEN: usize = IDENTITY_MAGIC.len() + size_of::<u16>() + SECRET_KEY_LEN;
static TEMP_FILE_COUNTER: AtomicU64 = AtomicU64::new(0);

/// The persistent identity envelope version understood by this crate.
pub const IDENTITY_FORMAT_VERSION: u16 = 1;

/// The exact byte length of a Foundation M4 identity envelope.
pub const IDENTITY_FILE_LEN: usize = PREFIX_LEN + CHECKSUM_LEN;

/// Failures loading, creating, or validating persistent device identity.
#[derive(Debug, Error)]
pub enum IdentityError {
    /// A filesystem operation failed.
    #[error("identity {operation} failed: {source}")]
    Io {
        /// The bounded operation that failed.
        operation: &'static str,
        #[source]
        source: io::Error,
    },
    /// The identity path does not name a regular file.
    #[error("identity path is not a regular file")]
    NotRegularFile,
    /// The existing identity ended before the fixed envelope length.
    #[error("identity is truncated: received {actual} of {expected} bytes")]
    TruncatedIdentity {
        /// Existing file length.
        actual: usize,
        /// Required file length.
        expected: usize,
    },
    /// The existing identity has bytes after its fixed envelope.
    #[error("identity has trailing data: received {actual} bytes, expected {expected}")]
    TrailingData {
        /// Existing file length.
        actual: usize,
        /// Required file length.
        expected: usize,
    },
    /// The envelope does not begin with Rift identity magic.
    #[error("identity has invalid magic")]
    InvalidMagic,
    /// The envelope version is not supported.
    #[error("unsupported identity version {0}")]
    UnsupportedVersion(u16),
    /// The envelope checksum does not match its prefix and secret bytes.
    #[error("identity checksum mismatch")]
    ChecksumMismatch,
    /// Unix permission bits would expose the secret outside the owning user.
    #[cfg(unix)]
    #[error("identity permissions {actual:o} expose secret key material; required mode is 600")]
    InsecurePermissions {
        /// Existing Unix permission bits.
        actual: u32,
    },
    /// The path cannot supply a file name for a same-directory temporary file.
    #[error("identity path has no file name")]
    MissingFileName,
}

/// One persistent Rift cryptographic identity.
#[derive(Clone)]
pub struct StoredIdentity {
    secret_key: SecretKey,
    device_id: DeviceId,
    path: PathBuf,
}

impl StoredIdentity {
    /// Returns the public device identity derived from the persisted Iroh key.
    pub const fn device_id(&self) -> DeviceId {
        self.device_id
    }

    /// Returns the identity storage path without exposing key material.
    pub fn path(&self) -> &Path {
        &self.path
    }

    /// Consumes this value and transfers the secret key to the endpoint owner.
    pub fn into_secret_key(self) -> SecretKey {
        self.secret_key
    }
}

impl fmt::Debug for StoredIdentity {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("StoredIdentity")
            .field("device_id", &self.device_id)
            .field("path", &self.path)
            .finish_non_exhaustive()
    }
}

/// Narrow persistent-identity storage operations.
pub struct IdentityStore;

impl IdentityStore {
    /// Loads a complete existing identity or atomically creates one when absent.
    ///
    /// Existing malformed identity always fails closed. It is never replaced or
    /// regenerated by this operation.
    pub fn load_or_create(path: impl AsRef<Path>) -> Result<StoredIdentity, IdentityError> {
        let path = path.as_ref();
        match fs::symlink_metadata(path) {
            Ok(_) => load(path),
            Err(error) if error.kind() == io::ErrorKind::NotFound => create(path),
            Err(source) => Err(io_error("inspect", source)),
        }
    }
}

fn load(path: &Path) -> Result<StoredIdentity, IdentityError> {
    let metadata = fs::symlink_metadata(path).map_err(|source| io_error("inspect", source))?;
    if !metadata.file_type().is_file() {
        return Err(IdentityError::NotRegularFile);
    }
    validate_permissions(&metadata)?;
    let length = usize::try_from(metadata.len()).unwrap_or(usize::MAX);
    if length < IDENTITY_FILE_LEN {
        return Err(IdentityError::TruncatedIdentity {
            actual: length,
            expected: IDENTITY_FILE_LEN,
        });
    }
    if length > IDENTITY_FILE_LEN {
        return Err(IdentityError::TrailingData {
            actual: length,
            expected: IDENTITY_FILE_LEN,
        });
    }
    let bytes = fs::read(path).map_err(|source| io_error("read", source))?;
    decode(path, &bytes)
}

fn create(path: &Path) -> Result<StoredIdentity, IdentityError> {
    let secret_key = SecretKey::generate();
    let encoded = encode(&secret_key);
    let (mut temporary, temporary_path) = create_temporary(path)?;
    let mut cleanup = TemporaryCleanup::new(temporary_path.clone());

    temporary
        .write_all(&encoded)
        .map_err(|source| io_error("write temporary file", source))?;
    temporary
        .flush()
        .map_err(|source| io_error("flush temporary file", source))?;
    temporary
        .sync_all()
        .map_err(|source| io_error("sync temporary file", source))?;
    apply_private_permissions(&temporary_path)?;
    let metadata = temporary
        .metadata()
        .map_err(|source| io_error("inspect temporary file", source))?;
    validate_permissions(&metadata)?;
    drop(temporary);

    match fs::hard_link(&temporary_path, path) {
        Ok(()) => {}
        Err(error) if error.kind() == io::ErrorKind::AlreadyExists => {
            cleanup.remove()?;
            return load(path);
        }
        Err(source) => return Err(io_error("promote temporary file", source)),
    }
    cleanup.remove()?;
    sync_parent(path)?;
    load(path)
}

fn encode(secret_key: &SecretKey) -> [u8; IDENTITY_FILE_LEN] {
    let mut encoded = [0_u8; IDENTITY_FILE_LEN];
    encoded[..IDENTITY_MAGIC.len()].copy_from_slice(IDENTITY_MAGIC);
    let version_start = IDENTITY_MAGIC.len();
    let version_end = version_start + size_of::<u16>();
    encoded[version_start..version_end].copy_from_slice(&IDENTITY_FORMAT_VERSION.to_be_bytes());
    encoded[version_end..PREFIX_LEN].copy_from_slice(&secret_key.to_bytes());
    let checksum = blake3::hash(&encoded[..PREFIX_LEN]);
    encoded[PREFIX_LEN..].copy_from_slice(checksum.as_bytes());
    encoded
}

fn decode(path: &Path, bytes: &[u8]) -> Result<StoredIdentity, IdentityError> {
    if bytes.len() < IDENTITY_FILE_LEN {
        return Err(IdentityError::TruncatedIdentity {
            actual: bytes.len(),
            expected: IDENTITY_FILE_LEN,
        });
    }
    if bytes.len() > IDENTITY_FILE_LEN {
        return Err(IdentityError::TrailingData {
            actual: bytes.len(),
            expected: IDENTITY_FILE_LEN,
        });
    }
    if &bytes[..IDENTITY_MAGIC.len()] != IDENTITY_MAGIC {
        return Err(IdentityError::InvalidMagic);
    }
    let version_start = IDENTITY_MAGIC.len();
    let version_end = version_start + size_of::<u16>();
    let version = u16::from_be_bytes([bytes[version_start], bytes[version_start + 1]]);
    if version != IDENTITY_FORMAT_VERSION {
        return Err(IdentityError::UnsupportedVersion(version));
    }
    let checksum = blake3::hash(&bytes[..PREFIX_LEN]);
    if !constant_time_equal(&bytes[PREFIX_LEN..], checksum.as_bytes()) {
        return Err(IdentityError::ChecksumMismatch);
    }
    let secret_bytes: [u8; SECRET_KEY_LEN] =
        bytes[version_end..PREFIX_LEN].try_into().map_err(|_| {
            IdentityError::TruncatedIdentity {
                actual: bytes.len(),
                expected: IDENTITY_FILE_LEN,
            }
        })?;
    let secret_key = SecretKey::from_bytes(&secret_bytes);
    let device_id = DeviceId::from_bytes(*secret_key.public().as_bytes());
    Ok(StoredIdentity {
        secret_key,
        device_id,
        path: path.to_path_buf(),
    })
}

fn constant_time_equal(left: &[u8], right: &[u8]) -> bool {
    if left.len() != right.len() {
        return false;
    }
    left.iter()
        .zip(right)
        .fold(0_u8, |difference, (left, right)| {
            difference | (left ^ right)
        })
        == 0
}

fn create_temporary(path: &Path) -> Result<(File, PathBuf), IdentityError> {
    let file_name = path
        .file_name()
        .and_then(|name| name.to_str())
        .ok_or(IdentityError::MissingFileName)?;
    loop {
        let counter = TEMP_FILE_COUNTER.fetch_add(1, Ordering::Relaxed);
        let temporary_path = path.with_file_name(format!(
            ".{file_name}.{}.{}.tmp",
            std::process::id(),
            counter
        ));
        let mut options = OpenOptions::new();
        options.write(true).create_new(true);
        #[cfg(unix)]
        {
            use std::os::unix::fs::OpenOptionsExt;
            options.mode(0o600);
        }
        match options.open(&temporary_path) {
            Ok(file) => return Ok((file, temporary_path)),
            Err(error) if error.kind() == io::ErrorKind::AlreadyExists => continue,
            Err(source) => return Err(io_error("create temporary file", source)),
        }
    }
}

struct TemporaryCleanup {
    path: Option<PathBuf>,
}

impl TemporaryCleanup {
    fn new(path: PathBuf) -> Self {
        Self { path: Some(path) }
    }

    fn remove(&mut self) -> Result<(), IdentityError> {
        let Some(path) = self.path.take() else {
            return Ok(());
        };
        fs::remove_file(path).map_err(|source| io_error("remove temporary file", source))
    }
}

impl Drop for TemporaryCleanup {
    fn drop(&mut self) {
        if let Some(path) = self.path.take() {
            drop(fs::remove_file(path));
        }
    }
}

#[cfg(unix)]
fn apply_private_permissions(path: &Path) -> Result<(), IdentityError> {
    use std::os::unix::fs::PermissionsExt;
    fs::set_permissions(path, fs::Permissions::from_mode(0o600))
        .map_err(|source| io_error("set permissions", source))
}

#[cfg(not(unix))]
fn apply_private_permissions(_path: &Path) -> Result<(), IdentityError> {
    Ok(())
}

#[cfg(unix)]
fn validate_permissions(metadata: &fs::Metadata) -> Result<(), IdentityError> {
    use std::os::unix::fs::PermissionsExt;
    let mode = metadata.permissions().mode() & 0o777;
    if mode != 0o600 {
        return Err(IdentityError::InsecurePermissions { actual: mode });
    }
    Ok(())
}

#[cfg(not(unix))]
fn validate_permissions(_metadata: &fs::Metadata) -> Result<(), IdentityError> {
    Ok(())
}

#[cfg(unix)]
fn sync_parent(path: &Path) -> Result<(), IdentityError> {
    let parent = path.parent().ok_or(IdentityError::MissingFileName)?;
    File::open(parent)
        .and_then(|directory| directory.sync_all())
        .map_err(|source| io_error("sync parent directory", source))
}

#[cfg(not(unix))]
fn sync_parent(_path: &Path) -> Result<(), IdentityError> {
    Ok(())
}

fn io_error(operation: &'static str, source: io::Error) -> IdentityError {
    IdentityError::Io { operation, source }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn write_private(path: &Path, bytes: &[u8]) -> Result<(), Box<dyn std::error::Error>> {
        fs::write(path, bytes)?;
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            fs::set_permissions(path, fs::Permissions::from_mode(0o600))?;
        }
        Ok(())
    }

    #[test]
    fn creates_and_reloads_exact_identity_without_debug_disclosure()
    -> Result<(), Box<dyn std::error::Error>> {
        let directory = tempfile::tempdir()?;
        let path = directory.path().join("identity.key");
        let first = IdentityStore::load_or_create(&path)?;
        let bytes = fs::read(&path)?;
        let secret_hex = hex::encode(first.secret_key.to_bytes());
        let debug = format!("{first:?}");

        assert_eq!(bytes.len(), IDENTITY_FILE_LEN);
        assert!(!debug.contains(&secret_hex));
        assert!(!debug.contains("secret_key"));
        let first_id = first.device_id();
        let second = IdentityStore::load_or_create(&path)?;
        assert_eq!(second.device_id(), first_id);
        assert_eq!(fs::read(path)?, bytes);
        Ok(())
    }

    #[test]
    fn corruption_and_unsupported_formats_fail_closed() -> Result<(), Box<dyn std::error::Error>> {
        let directory = tempfile::tempdir()?;
        let path = directory.path().join("identity.key");
        let identity = IdentityStore::load_or_create(&path)?;
        let valid = encode(&identity.secret_key);

        write_private(&path, &valid[..IDENTITY_FILE_LEN - 1])?;
        assert!(matches!(
            IdentityStore::load_or_create(&path),
            Err(IdentityError::TruncatedIdentity { .. })
        ));

        let mut wrong_magic = valid;
        wrong_magic[0] ^= 1;
        write_private(&path, &wrong_magic)?;
        assert!(matches!(
            IdentityStore::load_or_create(&path),
            Err(IdentityError::InvalidMagic)
        ));

        let mut unsupported = valid;
        unsupported[IDENTITY_MAGIC.len()..IDENTITY_MAGIC.len() + 2]
            .copy_from_slice(&2_u16.to_be_bytes());
        write_private(&path, &unsupported)?;
        assert!(matches!(
            IdentityStore::load_or_create(&path),
            Err(IdentityError::UnsupportedVersion(2))
        ));

        let mut bad_checksum = valid;
        bad_checksum[IDENTITY_FILE_LEN - 1] ^= 1;
        write_private(&path, &bad_checksum)?;
        assert!(matches!(
            IdentityStore::load_or_create(&path),
            Err(IdentityError::ChecksumMismatch)
        ));

        let mut trailing = valid.to_vec();
        trailing.push(0);
        write_private(&path, &trailing)?;
        assert!(matches!(
            IdentityStore::load_or_create(&path),
            Err(IdentityError::TrailingData { .. })
        ));
        Ok(())
    }

    #[cfg(unix)]
    #[test]
    fn identity_permissions_are_private_and_existing_exposure_fails_closed()
    -> Result<(), Box<dyn std::error::Error>> {
        use std::os::unix::fs::PermissionsExt;

        let directory = tempfile::tempdir()?;
        let path = directory.path().join("identity.key");
        IdentityStore::load_or_create(&path)?;
        assert_eq!(fs::metadata(&path)?.permissions().mode() & 0o777, 0o600);

        fs::set_permissions(&path, fs::Permissions::from_mode(0o640))?;
        assert!(matches!(
            IdentityStore::load_or_create(&path),
            Err(IdentityError::InsecurePermissions { actual: 0o640 })
        ));
        Ok(())
    }

    #[test]
    fn concurrent_creation_elects_one_complete_identity() -> Result<(), Box<dyn std::error::Error>>
    {
        let directory = tempfile::tempdir()?;
        let path = directory.path().join("identity.key");
        let barrier = std::sync::Arc::new(std::sync::Barrier::new(8));
        let handles = (0..8)
            .map(|_| {
                let path = path.clone();
                let barrier = std::sync::Arc::clone(&barrier);
                std::thread::spawn(move || {
                    barrier.wait();
                    IdentityStore::load_or_create(path)
                })
            })
            .collect::<Vec<_>>();
        let mut ids = Vec::new();
        for handle in handles {
            let identity = handle
                .join()
                .map_err(|_| io::Error::other("identity thread panicked"))??;
            ids.push(identity.device_id());
        }
        assert!(ids.windows(2).all(|pair| pair[0] == pair[1]));
        assert_eq!(fs::read(path)?.len(), IDENTITY_FILE_LEN);
        Ok(())
    }

    #[test]
    fn non_regular_identity_path_is_rejected() -> Result<(), Box<dyn std::error::Error>> {
        let directory = tempfile::tempdir()?;
        assert!(matches!(
            IdentityStore::load_or_create(directory.path()),
            Err(IdentityError::NotRegularFile)
        ));
        Ok(())
    }
}
