use std::{fmt, str::FromStr};

use serde::{Deserialize, Serialize};
use thiserror::Error;

/// The byte length of a logical transfer identifier.
pub const TRANSFER_ID_LEN: usize = 16;

/// A stable logical transfer identity, independent of a runtime session.
///
/// Production callers must supply bytes generated by the OS CSPRNG. Generation
/// and collision handling belong to the daemon, not this platform-independent type.
#[derive(Clone, Copy, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(transparent)]
pub struct TransferId([u8; TRANSFER_ID_LEN]);

impl TransferId {
    /// Constructs an identifier from exactly 16 bytes.
    pub const fn from_bytes(bytes: [u8; TRANSFER_ID_LEN]) -> Self {
        Self(bytes)
    }

    /// Returns the identifier's raw bytes.
    pub const fn as_bytes(&self) -> &[u8; TRANSFER_ID_LEN] {
        &self.0
    }

    /// Constructs an identifier from a slice of exactly 16 bytes.
    pub fn from_slice(bytes: &[u8]) -> Result<Self, TransferIdError> {
        let bytes = bytes.try_into().map_err(|_| TransferIdError::ByteLength)?;
        Ok(Self(bytes))
    }
}

impl From<[u8; TRANSFER_ID_LEN]> for TransferId {
    fn from(bytes: [u8; TRANSFER_ID_LEN]) -> Self {
        Self::from_bytes(bytes)
    }
}

impl AsRef<[u8]> for TransferId {
    fn as_ref(&self) -> &[u8] {
        self.as_bytes()
    }
}

impl FromStr for TransferId {
    type Err = TransferIdError;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        if value.len() != TRANSFER_ID_LEN * 2 {
            return Err(TransferIdError::TextLength);
        }
        if !value
            .bytes()
            .all(|byte| byte.is_ascii_digit() || (b'a'..=b'f').contains(&byte))
        {
            return Err(TransferIdError::NonCanonicalHex);
        }
        let mut bytes = [0; TRANSFER_ID_LEN];
        hex::decode_to_slice(value, &mut bytes).map_err(|_| TransferIdError::NonCanonicalHex)?;
        Ok(Self(bytes))
    }
}

impl fmt::Display for TransferId {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        for byte in self.0 {
            write!(formatter, "{byte:02x}")?;
        }
        Ok(())
    }
}

impl fmt::Debug for TransferId {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(formatter, "TransferId(\"{self}\")")
    }
}

/// Invalid raw bytes or noncanonical transfer identifier text.
#[derive(Clone, Copy, Debug, Eq, Error, PartialEq)]
pub enum TransferIdError {
    /// A raw identifier must contain exactly 16 bytes.
    #[error("transfer ID must contain exactly 16 bytes")]
    ByteLength,
    /// Text must contain exactly 32 UTF-8 bytes.
    #[error("transfer ID text must contain exactly 32 bytes")]
    TextLength,
    /// Only lowercase ASCII hexadecimal is canonical.
    #[error("transfer ID must be lowercase ASCII hexadecimal")]
    NonCanonicalHex,
}

#[cfg(test)]
mod tests {
    use std::collections::{BTreeSet, HashSet};

    use super::*;

    #[test]
    fn bytes_and_canonical_text_round_trip() -> Result<(), Box<dyn std::error::Error>> {
        let bytes = [
            0x00, 0x01, 0x0a, 0x0f, 0x10, 0x7f, 0x80, 0xff, 0, 1, 2, 3, 4, 5, 6, 7,
        ];
        let id = TransferId::from_bytes(bytes);
        assert_eq!(TRANSFER_ID_LEN, 16);
        assert_eq!(std::mem::size_of::<TransferId>(), 16);
        assert_eq!(id.as_bytes(), &bytes);
        assert_eq!(id.as_ref(), bytes);
        assert_eq!(TransferId::from_slice(&bytes)?, id);
        assert_eq!(TransferId::from(bytes), id);
        assert_eq!(id.to_string(), "00010a0f107f80ff0001020304050607");
        assert_eq!(id.to_string().parse::<TransferId>()?, id);
        assert_eq!(
            format!("{id:?}"),
            "TransferId(\"00010a0f107f80ff0001020304050607\")"
        );
        Ok(())
    }

    #[test]
    fn rejects_invalid_lengths_and_noncanonical_text() {
        for len in [0, 15, 17, 32] {
            assert_eq!(
                TransferId::from_slice(&vec![0; len]),
                Err(TransferIdError::ByteLength)
            );
        }
        for value in [
            "",
            "0",
            "0000000000000000000000000000000",
            "000000000000000000000000000000000",
        ] {
            assert_eq!(
                value.parse::<TransferId>(),
                Err(TransferIdError::TextLength)
            );
        }
        for value in [
            "A0000000000000000000000000000000",
            "g0000000000000000000000000000000",
            " 0000000000000000000000000000000",
            "0000000000000000000000000000000\n",
            "é000000000000000000000000000000",
        ] {
            assert_eq!(
                value.parse::<TransferId>(),
                Err(TransferIdError::NonCanonicalHex)
            );
        }
    }

    #[test]
    fn equality_ordering_and_hashing_use_all_bytes() {
        let low = TransferId::from_bytes([0; 16]);
        let mut bytes = [0; 16];
        bytes[15] = 1;
        let high = TransferId::from_bytes(bytes);
        assert!(low < high);
        assert_eq!(HashSet::from([low, high, low]).len(), 2);
        assert_eq!(
            BTreeSet::from([high, low, high])
                .into_iter()
                .collect::<Vec<_>>(),
            [low, high]
        );
    }

    #[test]
    fn serde_preserves_exact_raw_array() -> Result<(), Box<dyn std::error::Error>> {
        let bytes = [0xab; 16];
        let id = TransferId::from_bytes(bytes);
        let encoded = postcard::to_stdvec(&id)?;
        assert_eq!(encoded, bytes);
        assert_eq!(postcard::from_bytes::<TransferId>(&encoded)?, id);
        assert!(postcard::from_bytes::<TransferId>(&encoded[..15]).is_err());
        let json = serde_json::to_string(&id)?;
        assert_eq!(json, serde_json::to_string(&bytes)?);
        assert_eq!(serde_json::from_str::<TransferId>(&json)?, id);
        assert!(serde_json::from_str::<TransferId>("[]").is_err());
        assert!(serde_json::from_str::<TransferId>("[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]").is_err());
        Ok(())
    }
}
